GET http://localhost:3333/people

###
GET http://localhost:3333/people/6217898d895da4b2d31b26d4
###

POST http://localhost:3333/people/
Content-Type: application/json

{
"name": "Jane Doe",
"email": "jane@doe.com"
}

###
PATCH http://localhost:3333/people/6217aa42d037c2c138d6fa78
Content-Type: application/json

{
  "name": "John Doe"
}

###
DELETE http://localhost:3333/people/62177232895da4b2d31b26d1
